package.xml
rosrun (from rosbash) is required by the env-hooks for auto completion. Without that, sourcing setup.bash fails.
=> Fix package manifest file

CMakeLists.txt, src/gui/mon_gui.cpp, src/gui/mon_gui.ui, src/gui/rosmon_model.h, src/monitor/monitor.cpp, src/monitor/monitor.h
Adds some graceful fallbacks for Qt5 and roscpp features, so that rosmon compiles again under ROS Indigo.
See #9.
=> Indigo support

src/launch/launch_config.cpp
Example:
```
<launch>
<arg name="test" value="abcde
fghij" />
</launch>
```
With this PR, rosmon produces `"abcde fghij"`, which is at least closer to roslaunch's `"abcde  fghij"` (two spaces!). It should at least fix issues with whitespace at begin/end of the value, such as #16.
Edit: the second string is not displayed by GitHub's markdown properly and there is no easy way to make it happen. Imagine two spaces between the words. Kind of ironic to hit this in an issue about whitespace simplification...
=> Simplify whitespace in <arg> tags

src/ui.cpp
Sometimes, C is a pain.
Fixes #19.
=> ui: calculate node name padding correctly on 32 bit architectures

CMakeLists.txt, src/launch/launch_config.cpp, src/launch/launch_config.h, src/launch/node.cpp, src/launch/node.h, test/basic.launch, test/basic.py, test/xml/node_utils.cpp, test/xml/node_utils.h, test/xml/test_node.cpp, test/xml/test_remap.cpp
Essentially, `<remap>` behaves like `<env>`, so treat it the same way.
This also adds unit tests and an integration test for global `<remap>`.
=> Support <remap> in other scopes than <node>

CMakeLists.txt, src/launch/substitution_python.cpp
This adds support for Python 3 *and* makes sure that we select the correct Python version that does not clash with system python (i.e. the version that rospack uses).
This fixes compilation on Debian Jessie.
=> Support Python 3 & select appropriate Python version

src/launch/launch_config.cpp, test/xml/test_rosparam.cpp
Make sure that we create string parameters for quoted YAML scalars. This fixes #33.
=> YAML quoted strings

CMakeLists.txt, src/launch/launch_config.cpp, src/launch/launch_config.h, src/launch/substitution_python.cpp, src/launch/substitution_python.h, src/launch/yaml_params.cpp, src/launch/yaml_params.h, test/xml/param_utils.h, test/xml/test_rosparam.cpp
[rosparam] supports some additional syntactic elements in its YAML input, such as degree/radian conversions. This PR adds support for:
* `deg(...)` and `rad(...)` with arbitrary Python expressions inside
* `!degrees` and `!radians` YAML tags
* Support for the YAML `!!binary` tag (gets put into a Base64 XmlRpcValue)
* Fixes support for `!!int`, `!!str`, `!!bool`, `!!float`.
Unit tests for all of these are also added.
[rosparam]: https://wiki.ros.org/rosparam
=> More complete support for rosparam features

src/logger.cpp, src/logger.h, src/main.cpp
Add --flush option that will flush the logfile after each entry.
In most cases you want your logfile to be synced with the output of the application. I think that most loggers do flush the output after each entry.
=> main: Add option for flushing the logfile

src/gui/mon_gui.cpp, src/gui/node_model.cpp, src/gui/node_model.h
Fix a bug that could lead to performing start/stop actions on wrong nodes.
This happened because the index used to determine the node those actions
should be performed on was the one returned by the view, which is the
index of the proxy model. This may be different than the one of the real
model.
You can replicate this bug if you use the rosmon plugin on an instance with multiple nodes. If you change the sorting by clicking on the header of a column and then try to perform a start/stop action on a node whose entry in the table got moved, you'll see that the action gets performed on a wrong node.
=> gui: Fix index bug in showContextMenu

src/main.cpp
If this option is set, rosmon will not automatically start the nodes in
the beginning.
There are cases where you would like to programmatically control the whole life-circle of a node. In those cases, you wouldn't want rosmon to automatically start the node.
=> Add --no-start option

src/launch/launch_config.cpp, src/launch/launch_config.h, src/launch/node.cpp, src/launch/node.h, src/main.cpp, src/monitor/monitor.cpp, src/monitor/monitor.h, src/monitor/node_monitor.cpp, src/monitor/node_monitor.h
This patch introduces the --shutdown-timeout option that gives the user
the ability to specify the time to wait for the nodes to shutdown after
the initial termination signal is sent.
=> Add option for controlling the shutdown timeout

src/package_registry.cpp
As mentioned in #45 we might have directories or other "special" files
with the same name.
=> package_registry: getExecutableInPath: check that we have a regular file

src/launch/launch_config.cpp, test/basic.launch, test/basic.py, test/nested.launch
This allows nested configurations like the one mentioned in #46.
=>  launch_config: respect ROS_NAMESPACE variable

src/launch/launch_config.cpp, src/launch/launch_config.h, test/xml/test_param.cpp
We now use `ros::names::clean()` for manipulation (concatenation) of ROS namespace names.
This fixes problems with double slashes as reported in #49.
=> Clean namespace names properly

test/basic.py
I somehow got confused and assumed that the test node was running inside
rosmon - when it was not (it is launched in the external rostest instance).
So we need to wait until rosmon has started before checking parameters etc.
This should fix #42.
=> test/basic: wait for rosmon to start up before running tests

src/launch/launch_config.cpp, test/xml/test_include.cpp
roslaunch allows this, so we should as well. Since it seems a bit
confusing, we issue a warning when this happens.
In these cases, `<arg value="XY">` should be applicable and is much clearer.
This also includes a unit test in `test/xml/include`.
=> launch: allow <arg default="XY"> in <include> tags

src/main.cpp
See #59 for motivation. `roslaunch` reacts to SIGTERM and SIGHUP as well.
=> main: exit gracefully on SIGTERM and SIGHUP as well

src/main.cpp
As detailed in #61, changing the default behavior from aborting to waiting should be safe.
=> main: wait for roscore if not already running, refs #61

src/launch/launch_config.cpp, test/xml/test_param.cpp
As noticed by Arturo in #66, we do not check for file errors correctly. We now check for
`!stream`, which checks for both `bad` and `fail` conditions.
Reference: http://www.cplusplus.com/reference/ios/ios/operator_not/
This also adds a corresponding unit test for the textfile case.
=> Fix file error checks

src/main.cpp
Mimic the behavior of `ROSCONSOLE_STDOUT_LINE_BUFFERED` for `rosconsole`.
Only applied in `--disable-ui` mode.
I went ahead and replaced #64 by a command line argument.
Feel free to arrange the implementation and change the argument name if you wish.
=> Add --flush-stdout option to flush stdout after each entry

rosmon_core/CMakeLists.txt, rqt_rosmon/CMakeLists.txt
In the current master, it looks like if you build the whole package from scratch using `catkin_make` there is no guarantee that `rosmon_msgs` would be built first before `rqt_rosmon` or `rosmon_core`, resulting in dependency errors down the line. I added a couple lines in the `CMakeLists.txt` to ensure that there are proper dependencies for the build targets in both packages to `rosmon_msgs`
=> Fix Rosmon build order

rosmon_core/src/terminal.cpp, rosmon_core/src/terminal.h, rosmon_core/src/ui.cpp, rosmon_core/src/ui.h
I added a feature that allows the user to filter the ros log outputs on the node(s) they select. This only affects the ncurses ui, and does not propagate to the logging mechanism; just the ui output. Useful for specifically trying to debug a particular node that crashed by observing it's output if other nodes are producing too much output to easily see. 
Usage: 
Select node as usual, and press f to filter. The foreground text color will become white to denote filtered node. 
Upon filtering the first node, all other nodes will be filtered out until the last filtered node is unfiltered. 
To unfilter, select filtered node and press f again.
Did my best to keep variable naming conventions and bracketing consistent with source file.
=> Feature: Added filtering ability to ncurses ui for node output streams

rosmon_core/src/launch/launch_config.cpp, rosmon_core/test/xml/test_arg.cpp, rosmon_core/test/xml/test_param.cpp
Non-lowercase bool values were partially addressed here: https://github.com/xqms/rosmon/pull/27/commits/488c8c03885dd73b878355b583371ecffb3c557b
This adds "True" input to some unit tests and converts to lowercase before comparing to true or false.
=> parse bool param case-insensitive

rosmon_core/src/launch/substitution_python.cpp, rosmon_core/test/xml/test_subst.cpp
For compatibility with `roslaunch`.
Fixes #84.
=> Handle lowercase true/false in $(eval) expressions

rosmon_core/CMakeLists.txt, rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/string_utils.cpp, rosmon_core/src/launch/string_utils.h, rosmon_core/src/launch/substitution.cpp, rosmon_core/test/xml/test_arg.cpp
`roslaunch` parses weird stuff like `$(arg    my_arg     )` without problems, so we should, too.
This fixes #83.
=> Trim & simplify whitespace in substitution contexts

rosmon_core/src/monitor/monitor.cpp
We use boost::filesystem to check if the stat file exists. It seems that
`fs::exists` handles ESRCH (which procfs may return in some cases, see #81)
as an exception, which is then unhandled by us.
Instead of catching the exception, we can just remove the check since
`readStatFile()` handles any error on opening the stat file correctly and
causes a `continue` in the process iteration loop.
This should fix #81.
=> rosmon_core: monitor: remove `exists` check for /proc/.../stat

rosmon_core/CMakeLists.txt, rosmon_core/src/monitor/node_monitor.cpp, rosmon_core/src/monitor/shim.cpp
After fork(), we should only use signal-safe standard library methods. So do all the complicated steps in an external executable that is executed first.
This fixes #88.
=> rosmon_core: monitor: make fork() operation safe using external shim

rosmon_core/src/diagnostics_publisher.cpp
When we get a warning that 'restart count > 0' we'd like to know how often. 
There is a difference if it happens occasionally or if it is a continuously increasing number.
Feel free to cherry-pick one of both commits if you think it is too redundant.
=> Add restart count to diagnostics

.travis.yml, rosmon_core/src/monitor/shim.cpp
See #102 for report. This also adds a travis CI job with `-fsanitize=address` to check this. While ASan does not report a failure, it seems to reliably trigger the bug.
=> rosmon_core: Correctly terminate execvp() arguments

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h, rosmon_core/src/launch/substitution.cpp, rosmon_core/test/xml/node_utils.cpp, rosmon_core/test/xml/test_subst.cpp
Basically, we need to handle `$(anon)` in the parse context, since it has scope. See #100 for detailed issue description.
This PR also changes a lot of the attribute parsing code (attributes need to be evaluated outside of their element's context for this to work). Needs verification in more complex setups.
=> Handle nesting with $(anon) subst correctly

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h, rosmon_core/src/launch/node.cpp, rosmon_core/src/launch/node.h, rosmon_core/src/log_event.h, rosmon_core/src/main.cpp, rosmon_core/src/monitor/node_monitor.cpp, rosmon_core/src/monitor/node_monitor.h, rosmon_core/src/ui.cpp, rosmon_core/src/ui.h, rosmon_core/test/xml/test_node.cpp
This is a refactored version of #108. If `--output-attr=obey` is given on the command line, actually parse the `output="screen|log"` attributes and use them to initialize the muting system.
This also refactors the muting system by moving the mute state into the `NodeMonitor` instance. That way, we don't have to track separate "muted" sets.
=> Option to obey output=XY tags

rosmon/src/rosmon, rosmon_core/env-hooks/50-rosmon.bash
fix #110
I changed `$*` to `"$@"` because `$*` divides args and it causes bugs.
=> Fix Issue "Can not handle arguments with spaces"

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h, rosmon_core/src/main.cpp, rosmon_core/src/monitor/node_monitor.cpp
For nodes that have their own terminal UI, rosmon should not interfere with that. We already had the `--disable-ui` flag for that, but this PR fixes some bugs and also allows to set this flag from the launch file.
=> Improved support for nodes with terminal UI

rosmon_core/src/launch/launch_config.cpp
`rosmon` has a different behavior compared to `roslaunch` in case of loading an empty yaml file.
I created a minimal example [here](https://github.com/marco-tranzatto/launch_file_examples/tree/master/rosmon_empty_yaml_issue).
The launch file "main.launch" contains a simple node that loads parameters from two different yaml files. The first file contains one parameters whereas the second one does not contain any "yaml node" to load. 
If the user executes
```
roslaunch rosmon_empty_yaml_issue main.launch
```
Then the launch succeeds. On the other hand, if the user executes
```
mon launch rosmon_empty_yaml_issue main.launch
```
Then the following error is reported:
```
Could not load launch file: /home/marcot/temp_ws/src/launch_file_examples/rosmon_empty_yaml_issue/launch/main.launch:10: …
```
=> Handle empty yaml file

rosmon_core/src/launch/launch_config.cpp, rosmon_core/test/xml/test_rosparam.cpp
Addresses #106.
Hello again @xqms. Over the past year I made a number of improvements and fixes to rosmon in one of my projects. I'll be rolling out these changes into PR's over the next few days.
This is a patch that enables YAML merge key functionality and somewhat addresses #106. While I am aware that `yaml-cpp` is technically the responsible party, their MR has still not yet been resolved, and `YAML` proper is partially to blame. Given that we really needed this, I made this patch for my team's purposes and successfully saved a lot of time our our end being able to use YAML anchors.
Here is an example `yaml` file I ran this patch over with success:
```yaml
common: &common
flux_a: 2.4
type_f: "vv_2de119"
stable: true
u_val: 3.0e-5
base_params: &base_params
class1:
x_var: 3.4
y_var: 1.3 …
```
=> rosmon_core: Add YAML merge key parsing functionality.

rosmon_core/package.xml
Necessary for ROS Noetic, where Python 2 is not available anymore. See #120.
=> rosmon_core: depend on python2/3 conditioned on ROS_PYTHON_VERSION

rosmon_core/src/launch/launch_config.cpp
This was a really insidious and potentially controversial patch we needed to make to `rosmon` to handle some undocumented behavior of `roslaunch`.
The tl;dr is that `roslaunch` parses all `<rosparam>` tags before it parses all `<param>` tags. This is in contrast to what `rosmon` does:
```cpp
for(TiXmlNode* n = element->FirstChild(); n; n = n->NextSibling())
{
.
.
.
if(e->ValueStr() == "param")
parseParam(e, ctx, PARAM_IN_NODE);
else if(e->ValueStr() == "rosparam")
parseROSParam(e, ctx);
else if(e->ValueStr() == "remap")
parseRemap(e, ctx);
else if(e->ValueStr() == "env")
}
```
This manifested itself as a really annoying bug when we were working with [mavros](http://wiki.ros.org/mavros). Specifically [this launch file](https://github.com/mavlink/mavros/blob/master/mavros/launch/node.launch) …
=> rosmon_core: Adding fix for rosparam parsing to equivilate with undocumented behavior of roslaunch

rosmon_core/src/ui.cpp, rosmon_core/src/ui.h
This was an important update to significantly reduce the 'idle' bandwidth on wireless low-bandwidth networks. This improves usability over ssh/mosh to remote nodes.
The way rosmon's update function seems to work is that it's called at a nominal rate of 10Hz, regardless of what's going on in the console screen. This was readily apparent when using `mosh` paired with Wireshark, where observing ~60 nodes all muted (so no new information is being printed), rosmon consumed ~50 kbps on average. All of this was from re-rendering the multitude of node status bars at a nominal rate of 10Hz.
So what this patch does is it gates the actual updating against a boolean that's set to true only on user key events and logging events. The same scenario described above with this patch effectively makes the …
=> rosmon_core: ui: UI DrawStatus optimized to only refresh on events.

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h, rosmon_core/src/main.cpp, rosmon_core/test/basic.py, rosmon_core/test/basic_sub.launch, rosmon_core/test/xml/test_include.cpp, rosmon_core/test/xml/test_node.cpp
This addresses #116 by supporting the following attributes on all scopes (`launch`, `group`, `node`, `include`):
* `enable-coredumps`
* `rosmon-memory-limit`
* `rosmon-cpu-limit`
* `rosmon-stop-timeout`
This makes it possible to include launch files designed for roslaunch, but adjust the rosmon-specific parameters at least globally.
=> Support certain attributes on all scopes

rosmon_core/src/monitor/node_monitor.cpp, rosmon_core/src/monitor/node_monitor.h, rosmon_core/test/abort.launch
This addresses #107 by the following two changes:
* direct support for `systemd-coredump`, which then manages core dump storage for us.
* if `systemd-coredump` is not installed / not active, then we at least delete core dumps from two runs ago - such that only the last core dump is kept.
=> Prevent infinite coredump aggregation & support systemd-coredump

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/node.cpp, rosmon_core/src/launch/node.h, rosmon_core/src/log_event.h, rosmon_core/src/monitor/node_monitor.cpp, rosmon_core/src/monitor/node_monitor.h, rosmon_core/src/monitor/shim.cpp, rosmon_core/src/ui.cpp, rosmon_core/src/ui.h, rosmon_core/test/xml/test_node.cpp
Here's yet another filter I added to `rosmon`. This was a bit tricky to get proper, but the tl;dr is that this uses the `fgColor` value to determine the log level. The reason why I went this route was a couple of reasons:
- We already get `fgColor` and it's simple to implement.
- When I checked the raw strings, there are actually subtle control character differences between C++ and Python ROS console output for the same log levels, which makes any non-color based solution inherently more complex.
I added F6, F7, and F8 as keys to select the verbosity level. Currently I just have it set to display levels 1, 2, and 3, but if you want I can change it to show 'Low, Med, High' or some effect. 
- 1 : Only `WARN`+ messages printed 
- 2 : Only `INFO`+ messages printed
- 3 : `DEBUG`+ messages …
=> rosmon_core: Adding verbosity filter feature

rosmon_core/src/launch/launch_config.cpp, rosmon_core/test/xml/test_rosparam.cpp
See #130 for bug report and example. Basically, `roslaunch` respects leading slashes during key resolution, we don't. There's no spec on this and I don't know what's better, but we have to match whatever `roslaunch` is doing, as always.
=> Respect leading slashes in rosparam YAML keys

rosmon_core/src/launch/bytes_parser.h
Fixes #136. Thanks to @andrewjong for reporting. Somehow on the CI machines and the usual systems I compile on `<tuple>` seems to include `<string>`. Weird...
=> core: launch: bytes_parser: add missing include

rosmon_core/src/main.cpp
Added a new option `--stdout-print-source` which when used in combination with `--disable-ui` prepends the source (i.e. node name) in parentheses to log lines printed to stdout.
Addresses #139 
Background:
I use rosmon with `--disable-ui` and `--flush-stdout` to run launch files from a systemd service. This is a great combination as the logs can be managed via journalctl. However, the node name is not included in the log line so it makes diagnostics difficult when reviewing the logs.
The standard rosmon TUI prints the node name in a coloured box at the start of each log line, so I figured it wouldn't be too far-fetched to do something similar when `--disable-ui` is used.
Perhaps a format string might be a more flexible option for the future, but this simple switch fixed my issue for now.
=> Added option to prepend node name to stdout when using --disable-ui.

rosmon_core/package.xml
boost dependencies became more fine-grained I believe.
But without this, the package doesn't compile.
=> Add missing dependency on libboost-python-dev

rosmon_core/src/diagnostics_publisher.cpp
In some of our use-cases it is especially useful to see when a node is stopped/idle.
=> Inidicate when a node is actually Idle (e.g. stopped)

rosmon_core/src/monitor/node_monitor.cpp, rosmon_core/src/monitor/node_monitor.h
Linux creates a new unix98 pty with the `ONLCR` flag set, see:
[pty.c:941](https://elixir.bootlin.com/linux/v5.13.5/source/drivers/tty/pty.c#L941)
and [tty_io.c:125](https://elixir.bootlin.com/linux/v5.13.5/source/drivers/tty/tty_io.c#L125).
The flag [ONLCR](https://www.gnu.org/software/libc/manual/html_node/Output-Modes.html#index-ONLCR) replaces `\n` with `\r\n` as done in [n_tty.c:444](https://elixir.bootlin.com/linux/v5.13.5/source/drivers/tty/n_tty.c#L444).
This can be an issue while using rosmon in a Docker container with the journald log driver.
Docker removes the trailing `\n` in log lines [here](https://github.com/moby/moby/blob/1f42dd5e91a643d8d4e3ef009fc8ba6e78c391d1/daemon/logger/copier.go#L104-L111).
This might not be obvious, but it is tested …
=> Clear ONLCR o_flag on pty to avoid converting \n into \r\n

rosmon_core/src/launch/yaml_params.cpp, rosmon_core/test/xml/test_rosparam.cpp
This should fix #150, where problems with the non-standard YAML merge keys `<<` inside arrays were noticed:
```yaml
defaults: &defaults
A: 1
B: 2
array:
- <<: *defaults
A: 23
C: 99
```
Previously, merge keys where only handled on a per-parameter level. Since arrays are imported onto the ROS parameter server as a single XmlRpcValue, merge keys inside were not handled at all. We now do that inside `yamlToXmlRpc()`, which fixes this situation.
It also adds a rudimentary unit test.
=> core/launch: support YAML merge keys inside arrays

rosmon_core/src/launch/launch_config.cpp, rosmon_core/test/basic.launch, rosmon_core/test/basic.py
This commit addresses differences between `rosmon` and `roslaunch` when parsing a nested global `group` namespace (`ns`) tag. If a nested `group` contains a global `ns` tag, it is no longer appended to the parent group.
Resolves xqms#160
=> Adds Check for Global Group Namespace Tag

rosmon_core/src/launch/yaml_params.cpp, rosmon_core/test/xml/test_rosparam.cpp
=> rosparam: strip whitespace inside deg() and rad() expressions

rosmon/CMakeLists.txt
Fixes issue #165. Previously, we installed the wrapper shell script via `catkin_install_python()`, which is obviously wrong. Just install it using `install(PROGRAMS ...)` instead and everything works fine in devel and install spaces.
=> rosmon: Fix installation of wrapper script in devel spaces

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h
This adds support for a `rosmon-import-args` attribute on the `<include>` tag. When set to `true`, rosmon will import all args set in the included file into the current scope.
=> core: support importing args from included files

rosmon_core/src/main.cpp
=> core: main: hide stdout log events if output=screen and UI is disabled (#170)

rosmon_core/src/launch/substitution_python.cpp
Fixes:
```
$SRC_DIR/ros-noetic-rosmon-core/src/work/src/launch/substitution_python.cpp: In function 'boost::python::api::object rosmon::launch::make_handler(F)':
$SRC_DIR/ros-noetic-rosmon-core/src/work/src/launch/substitution_python.cpp:32:29: error: 'vector' is not a member of 'boost::mpl'; did you mean 'vector'?
32 |                 boost::mpl::vector<std::string, const std::string&>()
|                             ^~~~~~
|                             vector9
```
=> Add missing include to #include <boost/mpl/vector.hpp>

rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h, rosmon_core/src/main.cpp
Hi,
We are using rosmon on some big launch files (> 100 nodes).
Launching all the nodes simultaneously gives us some problems on startup.
I added an option to auto increment the spawn delay of all the nodes (except those having already a spawn-delay set).
For example, with `--auto-increment-spawn-delay=1`
Node A will launch at 0s
Node B will launch at 1s
Node C will launch at 2s
=> add auto-increment-spawn-delay feature

rosmon_core/CMakeLists.txt, rosmon_core/src/launch/launch_config.cpp, rosmon_core/src/launch/launch_config.h, rosmon_core/src/log_event.h, rosmon_core/src/logger.cpp, rosmon_core/src/logger.h, rosmon_core/src/main.cpp, rosmon_core/src/monitor/log_parser.cpp, rosmon_core/src/monitor/log_parser.h, rosmon_core/src/monitor/monitor.cpp, rosmon_core/src/monitor/node_monitor.cpp, rosmon_core/src/monitor/node_monitor.h, rosmon_core/src/ui.cpp, rosmon_core/test/monitor/test_log_parser.cpp, rosmon_core/test/test_node.py
Instead of writing our own log files, we send our log output to the systemd journal (or BSD-style `/dev/log` via `syslog()`).
Components of this PR:
=> Systemd-journal & syslog support

rosmon_core/src/monitor/log_parser.cpp, rosmon_core/test/monitor/test_log_parser.cpp
Something like `"\e[33m First \e[0m and \e[32m second \e[0m"` would lead to rosmon only outputting `"First"`.
This also adds a corresponding test case.
See #178.
=> core: log_parser: fix state machine for multiple colored sections

rosmon_core/src/ros_interface.cpp, rosmon_core/test/basic.py, rosmon_msgs/srv/StartStop.srv
Discussion here: https://github.com/xqms/rosmon/issues/167#issue-1291311824
In Rosmon service call, allow regex.
Specifying node=".*" would allow starting/stopping all nodes. `/abcde/.*` would only affect nodes in the `abcde` namespace.
=> Add ROS Service logic to start/stop with regex
